#!/bin/bash
cd `dirname $0`
BASEDIR=`pwd`/build
export PATH=$BASEDIR/bin:$PATH
export LD_LIBRARY_PATH=$BASEDIR/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=$BASEDIR/lib:$LIBRARY_PATH
export C_INCLUDE_PATH=`pwd`/include:$C_INCLUDE_PATH
